/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesSelectRouteImport } from './routes/workspaces.select'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AppWorkspaceSlugRouteRouteImport } from './routes/app/$workspaceSlug/route'
import { Route as AppWorkspaceSlugIndexRouteImport } from './routes/app/$workspaceSlug/index'
import { Route as AuthSignupVerifyRouteImport } from './routes/auth.signup.verify'
import { Route as AuthInvitationsAcceptRouteImport } from './routes/auth.invitations.accept'
import { Route as AuthDesktopVerifyRouteImport } from './routes/auth.desktop.verify'
import { Route as AppWorkspaceSlugSettingsRouteRouteImport } from './routes/app/$workspaceSlug/settings/route'
import { Route as AppWorkspaceSlugSettingsIndexRouteImport } from './routes/app/$workspaceSlug/settings/index'
import { Route as AppWorkspaceSlugChatsIndexRouteImport } from './routes/app/$workspaceSlug/chats/index'
import { Route as AppWorkspaceSlugChatsCapturedSessionIdRouteImport } from './routes/app/$workspaceSlug/chats/$capturedSessionId'
import { Route as AppWorkspaceSlugSettingsWorkspaceIndexRouteImport } from './routes/app/$workspaceSlug/settings/workspace/index'
import { Route as AppWorkspaceSlugSettingsDevelopersIndexRouteImport } from './routes/app/$workspaceSlug/settings/developers/index'
import { Route as AppWorkspaceSlugSettingsAccountIndexRouteImport } from './routes/app/$workspaceSlug/settings/account/index'
import { Route as AppWorkspaceSlugSettingsWorkspaceMembersRouteImport } from './routes/app/$workspaceSlug/settings/workspace/members'
import { Route as AppWorkspaceSlugSettingsWorkspaceGeneralRouteImport } from './routes/app/$workspaceSlug/settings/workspace/general'
import { Route as AppWorkspaceSlugSettingsDevelopersMcpRouteImport } from './routes/app/$workspaceSlug/settings/developers/mcp'
import { Route as AppWorkspaceSlugSettingsDevelopersCliRouteImport } from './routes/app/$workspaceSlug/settings/developers/cli'
import { Route as AppWorkspaceSlugSettingsDevelopersApiRouteImport } from './routes/app/$workspaceSlug/settings/developers/api'
import { Route as AppWorkspaceSlugSettingsAccountSecurityRouteImport } from './routes/app/$workspaceSlug/settings/account/security'
import { Route as AppWorkspaceSlugSettingsAccountProfileRouteImport } from './routes/app/$workspaceSlug/settings/account/profile'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesSelectRoute = WorkspacesSelectRouteImport.update({
  id: '/workspaces/select',
  path: '/workspaces/select',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceSlugRouteRoute = AppWorkspaceSlugRouteRouteImport.update({
  id: '/$workspaceSlug',
  path: '/$workspaceSlug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkspaceSlugIndexRoute = AppWorkspaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceSlugRouteRoute,
} as any)
const AuthSignupVerifyRoute = AuthSignupVerifyRouteImport.update({
  id: '/auth/signup/verify',
  path: '/auth/signup/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInvitationsAcceptRoute = AuthInvitationsAcceptRouteImport.update({
  id: '/auth/invitations/accept',
  path: '/auth/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDesktopVerifyRoute = AuthDesktopVerifyRouteImport.update({
  id: '/auth/desktop/verify',
  path: '/auth/desktop/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceSlugSettingsRouteRoute =
  AppWorkspaceSlugSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWorkspaceSlugRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsIndexRoute =
  AppWorkspaceSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugChatsIndexRoute =
  AppWorkspaceSlugChatsIndexRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AppWorkspaceSlugRouteRoute,
  } as any)
const AppWorkspaceSlugChatsCapturedSessionIdRoute =
  AppWorkspaceSlugChatsCapturedSessionIdRouteImport.update({
    id: '/chats/$capturedSessionId',
    path: '/chats/$capturedSessionId',
    getParentRoute: () => AppWorkspaceSlugRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsWorkspaceIndexRoute =
  AppWorkspaceSlugSettingsWorkspaceIndexRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsDevelopersIndexRoute =
  AppWorkspaceSlugSettingsDevelopersIndexRouteImport.update({
    id: '/developers/',
    path: '/developers/',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsAccountIndexRoute =
  AppWorkspaceSlugSettingsAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsWorkspaceMembersRoute =
  AppWorkspaceSlugSettingsWorkspaceMembersRouteImport.update({
    id: '/workspace/members',
    path: '/workspace/members',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsWorkspaceGeneralRoute =
  AppWorkspaceSlugSettingsWorkspaceGeneralRouteImport.update({
    id: '/workspace/general',
    path: '/workspace/general',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsDevelopersMcpRoute =
  AppWorkspaceSlugSettingsDevelopersMcpRouteImport.update({
    id: '/developers/mcp',
    path: '/developers/mcp',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsDevelopersCliRoute =
  AppWorkspaceSlugSettingsDevelopersCliRouteImport.update({
    id: '/developers/cli',
    path: '/developers/cli',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsDevelopersApiRoute =
  AppWorkspaceSlugSettingsDevelopersApiRouteImport.update({
    id: '/developers/api',
    path: '/developers/api',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsAccountSecurityRoute =
  AppWorkspaceSlugSettingsAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)
const AppWorkspaceSlugSettingsAccountProfileRoute =
  AppWorkspaceSlugSettingsAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => AppWorkspaceSlugSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/$workspaceSlug': typeof AppWorkspaceSlugRouteRouteWithChildren
  '/auth/verify': typeof AuthVerifyRoute
  '/workspaces/select': typeof WorkspacesSelectRoute
  '/app/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsRouteRouteWithChildren
  '/auth/desktop/verify': typeof AuthDesktopVerifyRoute
  '/auth/invitations/accept': typeof AuthInvitationsAcceptRoute
  '/auth/signup/verify': typeof AuthSignupVerifyRoute
  '/app/$workspaceSlug/': typeof AppWorkspaceSlugIndexRoute
  '/app/$workspaceSlug/chats/$capturedSessionId': typeof AppWorkspaceSlugChatsCapturedSessionIdRoute
  '/app/$workspaceSlug/chats/': typeof AppWorkspaceSlugChatsIndexRoute
  '/app/$workspaceSlug/settings/': typeof AppWorkspaceSlugSettingsIndexRoute
  '/app/$workspaceSlug/settings/account/profile': typeof AppWorkspaceSlugSettingsAccountProfileRoute
  '/app/$workspaceSlug/settings/account/security': typeof AppWorkspaceSlugSettingsAccountSecurityRoute
  '/app/$workspaceSlug/settings/developers/api': typeof AppWorkspaceSlugSettingsDevelopersApiRoute
  '/app/$workspaceSlug/settings/developers/cli': typeof AppWorkspaceSlugSettingsDevelopersCliRoute
  '/app/$workspaceSlug/settings/developers/mcp': typeof AppWorkspaceSlugSettingsDevelopersMcpRoute
  '/app/$workspaceSlug/settings/workspace/general': typeof AppWorkspaceSlugSettingsWorkspaceGeneralRoute
  '/app/$workspaceSlug/settings/workspace/members': typeof AppWorkspaceSlugSettingsWorkspaceMembersRoute
  '/app/$workspaceSlug/settings/account/': typeof AppWorkspaceSlugSettingsAccountIndexRoute
  '/app/$workspaceSlug/settings/developers/': typeof AppWorkspaceSlugSettingsDevelopersIndexRoute
  '/app/$workspaceSlug/settings/workspace/': typeof AppWorkspaceSlugSettingsWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/workspaces/select': typeof WorkspacesSelectRoute
  '/auth/desktop/verify': typeof AuthDesktopVerifyRoute
  '/auth/invitations/accept': typeof AuthInvitationsAcceptRoute
  '/auth/signup/verify': typeof AuthSignupVerifyRoute
  '/app/$workspaceSlug': typeof AppWorkspaceSlugIndexRoute
  '/app/$workspaceSlug/chats/$capturedSessionId': typeof AppWorkspaceSlugChatsCapturedSessionIdRoute
  '/app/$workspaceSlug/chats': typeof AppWorkspaceSlugChatsIndexRoute
  '/app/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsIndexRoute
  '/app/$workspaceSlug/settings/account/profile': typeof AppWorkspaceSlugSettingsAccountProfileRoute
  '/app/$workspaceSlug/settings/account/security': typeof AppWorkspaceSlugSettingsAccountSecurityRoute
  '/app/$workspaceSlug/settings/developers/api': typeof AppWorkspaceSlugSettingsDevelopersApiRoute
  '/app/$workspaceSlug/settings/developers/cli': typeof AppWorkspaceSlugSettingsDevelopersCliRoute
  '/app/$workspaceSlug/settings/developers/mcp': typeof AppWorkspaceSlugSettingsDevelopersMcpRoute
  '/app/$workspaceSlug/settings/workspace/general': typeof AppWorkspaceSlugSettingsWorkspaceGeneralRoute
  '/app/$workspaceSlug/settings/workspace/members': typeof AppWorkspaceSlugSettingsWorkspaceMembersRoute
  '/app/$workspaceSlug/settings/account': typeof AppWorkspaceSlugSettingsAccountIndexRoute
  '/app/$workspaceSlug/settings/developers': typeof AppWorkspaceSlugSettingsDevelopersIndexRoute
  '/app/$workspaceSlug/settings/workspace': typeof AppWorkspaceSlugSettingsWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/$workspaceSlug': typeof AppWorkspaceSlugRouteRouteWithChildren
  '/auth/verify': typeof AuthVerifyRoute
  '/workspaces/select': typeof WorkspacesSelectRoute
  '/app/$workspaceSlug/settings': typeof AppWorkspaceSlugSettingsRouteRouteWithChildren
  '/auth/desktop/verify': typeof AuthDesktopVerifyRoute
  '/auth/invitations/accept': typeof AuthInvitationsAcceptRoute
  '/auth/signup/verify': typeof AuthSignupVerifyRoute
  '/app/$workspaceSlug/': typeof AppWorkspaceSlugIndexRoute
  '/app/$workspaceSlug/chats/$capturedSessionId': typeof AppWorkspaceSlugChatsCapturedSessionIdRoute
  '/app/$workspaceSlug/chats/': typeof AppWorkspaceSlugChatsIndexRoute
  '/app/$workspaceSlug/settings/': typeof AppWorkspaceSlugSettingsIndexRoute
  '/app/$workspaceSlug/settings/account/profile': typeof AppWorkspaceSlugSettingsAccountProfileRoute
  '/app/$workspaceSlug/settings/account/security': typeof AppWorkspaceSlugSettingsAccountSecurityRoute
  '/app/$workspaceSlug/settings/developers/api': typeof AppWorkspaceSlugSettingsDevelopersApiRoute
  '/app/$workspaceSlug/settings/developers/cli': typeof AppWorkspaceSlugSettingsDevelopersCliRoute
  '/app/$workspaceSlug/settings/developers/mcp': typeof AppWorkspaceSlugSettingsDevelopersMcpRoute
  '/app/$workspaceSlug/settings/workspace/general': typeof AppWorkspaceSlugSettingsWorkspaceGeneralRoute
  '/app/$workspaceSlug/settings/workspace/members': typeof AppWorkspaceSlugSettingsWorkspaceMembersRoute
  '/app/$workspaceSlug/settings/account/': typeof AppWorkspaceSlugSettingsAccountIndexRoute
  '/app/$workspaceSlug/settings/developers/': typeof AppWorkspaceSlugSettingsDevelopersIndexRoute
  '/app/$workspaceSlug/settings/workspace/': typeof AppWorkspaceSlugSettingsWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/create'
    | '/login'
    | '/onboarding'
    | '/app/$workspaceSlug'
    | '/auth/verify'
    | '/workspaces/select'
    | '/app/$workspaceSlug/settings'
    | '/auth/desktop/verify'
    | '/auth/invitations/accept'
    | '/auth/signup/verify'
    | '/app/$workspaceSlug/'
    | '/app/$workspaceSlug/chats/$capturedSessionId'
    | '/app/$workspaceSlug/chats/'
    | '/app/$workspaceSlug/settings/'
    | '/app/$workspaceSlug/settings/account/profile'
    | '/app/$workspaceSlug/settings/account/security'
    | '/app/$workspaceSlug/settings/developers/api'
    | '/app/$workspaceSlug/settings/developers/cli'
    | '/app/$workspaceSlug/settings/developers/mcp'
    | '/app/$workspaceSlug/settings/workspace/general'
    | '/app/$workspaceSlug/settings/workspace/members'
    | '/app/$workspaceSlug/settings/account/'
    | '/app/$workspaceSlug/settings/developers/'
    | '/app/$workspaceSlug/settings/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/create'
    | '/login'
    | '/onboarding'
    | '/auth/verify'
    | '/workspaces/select'
    | '/auth/desktop/verify'
    | '/auth/invitations/accept'
    | '/auth/signup/verify'
    | '/app/$workspaceSlug'
    | '/app/$workspaceSlug/chats/$capturedSessionId'
    | '/app/$workspaceSlug/chats'
    | '/app/$workspaceSlug/settings'
    | '/app/$workspaceSlug/settings/account/profile'
    | '/app/$workspaceSlug/settings/account/security'
    | '/app/$workspaceSlug/settings/developers/api'
    | '/app/$workspaceSlug/settings/developers/cli'
    | '/app/$workspaceSlug/settings/developers/mcp'
    | '/app/$workspaceSlug/settings/workspace/general'
    | '/app/$workspaceSlug/settings/workspace/members'
    | '/app/$workspaceSlug/settings/account'
    | '/app/$workspaceSlug/settings/developers'
    | '/app/$workspaceSlug/settings/workspace'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/create'
    | '/login'
    | '/onboarding'
    | '/app/$workspaceSlug'
    | '/auth/verify'
    | '/workspaces/select'
    | '/app/$workspaceSlug/settings'
    | '/auth/desktop/verify'
    | '/auth/invitations/accept'
    | '/auth/signup/verify'
    | '/app/$workspaceSlug/'
    | '/app/$workspaceSlug/chats/$capturedSessionId'
    | '/app/$workspaceSlug/chats/'
    | '/app/$workspaceSlug/settings/'
    | '/app/$workspaceSlug/settings/account/profile'
    | '/app/$workspaceSlug/settings/account/security'
    | '/app/$workspaceSlug/settings/developers/api'
    | '/app/$workspaceSlug/settings/developers/cli'
    | '/app/$workspaceSlug/settings/developers/mcp'
    | '/app/$workspaceSlug/settings/workspace/general'
    | '/app/$workspaceSlug/settings/workspace/members'
    | '/app/$workspaceSlug/settings/account/'
    | '/app/$workspaceSlug/settings/developers/'
    | '/app/$workspaceSlug/settings/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  WorkspacesSelectRoute: typeof WorkspacesSelectRoute
  AuthDesktopVerifyRoute: typeof AuthDesktopVerifyRoute
  AuthInvitationsAcceptRoute: typeof AuthInvitationsAcceptRoute
  AuthSignupVerifyRoute: typeof AuthSignupVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/select': {
      id: '/workspaces/select'
      path: '/workspaces/select'
      fullPath: '/workspaces/select'
      preLoaderRoute: typeof WorkspacesSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$workspaceSlug': {
      id: '/app/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/app/$workspaceSlug'
      preLoaderRoute: typeof AppWorkspaceSlugRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$workspaceSlug/': {
      id: '/app/$workspaceSlug/'
      path: '/'
      fullPath: '/app/$workspaceSlug/'
      preLoaderRoute: typeof AppWorkspaceSlugIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugRouteRoute
    }
    '/auth/signup/verify': {
      id: '/auth/signup/verify'
      path: '/auth/signup/verify'
      fullPath: '/auth/signup/verify'
      preLoaderRoute: typeof AuthSignupVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/invitations/accept': {
      id: '/auth/invitations/accept'
      path: '/auth/invitations/accept'
      fullPath: '/auth/invitations/accept'
      preLoaderRoute: typeof AuthInvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/desktop/verify': {
      id: '/auth/desktop/verify'
      path: '/auth/desktop/verify'
      fullPath: '/auth/desktop/verify'
      preLoaderRoute: typeof AuthDesktopVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$workspaceSlug/settings': {
      id: '/app/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/app/$workspaceSlug/settings'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsRouteRouteImport
      parentRoute: typeof AppWorkspaceSlugRouteRoute
    }
    '/app/$workspaceSlug/settings/': {
      id: '/app/$workspaceSlug/settings/'
      path: '/'
      fullPath: '/app/$workspaceSlug/settings/'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/chats/': {
      id: '/app/$workspaceSlug/chats/'
      path: '/chats'
      fullPath: '/app/$workspaceSlug/chats/'
      preLoaderRoute: typeof AppWorkspaceSlugChatsIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugRouteRoute
    }
    '/app/$workspaceSlug/chats/$capturedSessionId': {
      id: '/app/$workspaceSlug/chats/$capturedSessionId'
      path: '/chats/$capturedSessionId'
      fullPath: '/app/$workspaceSlug/chats/$capturedSessionId'
      preLoaderRoute: typeof AppWorkspaceSlugChatsCapturedSessionIdRouteImport
      parentRoute: typeof AppWorkspaceSlugRouteRoute
    }
    '/app/$workspaceSlug/settings/workspace/': {
      id: '/app/$workspaceSlug/settings/workspace/'
      path: '/workspace'
      fullPath: '/app/$workspaceSlug/settings/workspace/'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsWorkspaceIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/settings/developers/': {
      id: '/app/$workspaceSlug/settings/developers/'
      path: '/developers'
      fullPath: '/app/$workspaceSlug/settings/developers/'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsDevelopersIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/settings/account/': {
      id: '/app/$workspaceSlug/settings/account/'
      path: '/account'
      fullPath: '/app/$workspaceSlug/settings/account/'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsAccountIndexRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/settings/workspace/members': {
      id: '/app/$workspaceSlug/settings/workspace/members'
      path: '/workspace/members'
      fullPath: '/app/$workspaceSlug/settings/workspace/members'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsWorkspaceMembersRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/settings/workspace/general': {
      id: '/app/$workspaceSlug/settings/workspace/general'
      path: '/workspace/general'
      fullPath: '/app/$workspaceSlug/settings/workspace/general'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsWorkspaceGeneralRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/settings/developers/mcp': {
      id: '/app/$workspaceSlug/settings/developers/mcp'
      path: '/developers/mcp'
      fullPath: '/app/$workspaceSlug/settings/developers/mcp'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsDevelopersMcpRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/settings/developers/cli': {
      id: '/app/$workspaceSlug/settings/developers/cli'
      path: '/developers/cli'
      fullPath: '/app/$workspaceSlug/settings/developers/cli'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsDevelopersCliRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/settings/developers/api': {
      id: '/app/$workspaceSlug/settings/developers/api'
      path: '/developers/api'
      fullPath: '/app/$workspaceSlug/settings/developers/api'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsDevelopersApiRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/settings/account/security': {
      id: '/app/$workspaceSlug/settings/account/security'
      path: '/account/security'
      fullPath: '/app/$workspaceSlug/settings/account/security'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsAccountSecurityRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
    '/app/$workspaceSlug/settings/account/profile': {
      id: '/app/$workspaceSlug/settings/account/profile'
      path: '/account/profile'
      fullPath: '/app/$workspaceSlug/settings/account/profile'
      preLoaderRoute: typeof AppWorkspaceSlugSettingsAccountProfileRouteImport
      parentRoute: typeof AppWorkspaceSlugSettingsRouteRoute
    }
  }
}

interface AppWorkspaceSlugSettingsRouteRouteChildren {
  AppWorkspaceSlugSettingsIndexRoute: typeof AppWorkspaceSlugSettingsIndexRoute
  AppWorkspaceSlugSettingsAccountProfileRoute: typeof AppWorkspaceSlugSettingsAccountProfileRoute
  AppWorkspaceSlugSettingsAccountSecurityRoute: typeof AppWorkspaceSlugSettingsAccountSecurityRoute
  AppWorkspaceSlugSettingsDevelopersApiRoute: typeof AppWorkspaceSlugSettingsDevelopersApiRoute
  AppWorkspaceSlugSettingsDevelopersCliRoute: typeof AppWorkspaceSlugSettingsDevelopersCliRoute
  AppWorkspaceSlugSettingsDevelopersMcpRoute: typeof AppWorkspaceSlugSettingsDevelopersMcpRoute
  AppWorkspaceSlugSettingsWorkspaceGeneralRoute: typeof AppWorkspaceSlugSettingsWorkspaceGeneralRoute
  AppWorkspaceSlugSettingsWorkspaceMembersRoute: typeof AppWorkspaceSlugSettingsWorkspaceMembersRoute
  AppWorkspaceSlugSettingsAccountIndexRoute: typeof AppWorkspaceSlugSettingsAccountIndexRoute
  AppWorkspaceSlugSettingsDevelopersIndexRoute: typeof AppWorkspaceSlugSettingsDevelopersIndexRoute
  AppWorkspaceSlugSettingsWorkspaceIndexRoute: typeof AppWorkspaceSlugSettingsWorkspaceIndexRoute
}

const AppWorkspaceSlugSettingsRouteRouteChildren: AppWorkspaceSlugSettingsRouteRouteChildren =
  {
    AppWorkspaceSlugSettingsIndexRoute: AppWorkspaceSlugSettingsIndexRoute,
    AppWorkspaceSlugSettingsAccountProfileRoute:
      AppWorkspaceSlugSettingsAccountProfileRoute,
    AppWorkspaceSlugSettingsAccountSecurityRoute:
      AppWorkspaceSlugSettingsAccountSecurityRoute,
    AppWorkspaceSlugSettingsDevelopersApiRoute:
      AppWorkspaceSlugSettingsDevelopersApiRoute,
    AppWorkspaceSlugSettingsDevelopersCliRoute:
      AppWorkspaceSlugSettingsDevelopersCliRoute,
    AppWorkspaceSlugSettingsDevelopersMcpRoute:
      AppWorkspaceSlugSettingsDevelopersMcpRoute,
    AppWorkspaceSlugSettingsWorkspaceGeneralRoute:
      AppWorkspaceSlugSettingsWorkspaceGeneralRoute,
    AppWorkspaceSlugSettingsWorkspaceMembersRoute:
      AppWorkspaceSlugSettingsWorkspaceMembersRoute,
    AppWorkspaceSlugSettingsAccountIndexRoute:
      AppWorkspaceSlugSettingsAccountIndexRoute,
    AppWorkspaceSlugSettingsDevelopersIndexRoute:
      AppWorkspaceSlugSettingsDevelopersIndexRoute,
    AppWorkspaceSlugSettingsWorkspaceIndexRoute:
      AppWorkspaceSlugSettingsWorkspaceIndexRoute,
  }

const AppWorkspaceSlugSettingsRouteRouteWithChildren =
  AppWorkspaceSlugSettingsRouteRoute._addFileChildren(
    AppWorkspaceSlugSettingsRouteRouteChildren,
  )

interface AppWorkspaceSlugRouteRouteChildren {
  AppWorkspaceSlugSettingsRouteRoute: typeof AppWorkspaceSlugSettingsRouteRouteWithChildren
  AppWorkspaceSlugIndexRoute: typeof AppWorkspaceSlugIndexRoute
  AppWorkspaceSlugChatsCapturedSessionIdRoute: typeof AppWorkspaceSlugChatsCapturedSessionIdRoute
  AppWorkspaceSlugChatsIndexRoute: typeof AppWorkspaceSlugChatsIndexRoute
}

const AppWorkspaceSlugRouteRouteChildren: AppWorkspaceSlugRouteRouteChildren = {
  AppWorkspaceSlugSettingsRouteRoute:
    AppWorkspaceSlugSettingsRouteRouteWithChildren,
  AppWorkspaceSlugIndexRoute: AppWorkspaceSlugIndexRoute,
  AppWorkspaceSlugChatsCapturedSessionIdRoute:
    AppWorkspaceSlugChatsCapturedSessionIdRoute,
  AppWorkspaceSlugChatsIndexRoute: AppWorkspaceSlugChatsIndexRoute,
}

const AppWorkspaceSlugRouteRouteWithChildren =
  AppWorkspaceSlugRouteRoute._addFileChildren(
    AppWorkspaceSlugRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppWorkspaceSlugRouteRoute: typeof AppWorkspaceSlugRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppWorkspaceSlugRouteRoute: AppWorkspaceSlugRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  WorkspacesSelectRoute: WorkspacesSelectRoute,
  AuthDesktopVerifyRoute: AuthDesktopVerifyRoute,
  AuthInvitationsAcceptRoute: AuthInvitationsAcceptRoute,
  AuthSignupVerifyRoute: AuthSignupVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
