// @generated drizzle-zero signature:sha256:ebefc5184fbaaec4aa492dac16f5d0c52671e3215c67b48ae3dc52df4af8474d
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const capturedSessionArtifactsTable = {
    "name": "capturedSessionArtifacts",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "capturedSessionId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "captured_session_id"
        },
        "capturedMessageId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "captured_message_id"
        },
        "fileObjectId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "file_object_id"
        },
        "artifactKind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "artifact_kind"
        },
        "sourceArtifactId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "source_artifact_id"
        },
        "sourceArtifactKey": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "source_artifact_key"
        },
        "title": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "contentType": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "content_type"
        },
        "metadataJson": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "metadata_json"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "captured_session_artifacts"
} as const;
const capturedSessionMessagesTable = {
    "name": "capturedSessionMessages",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "capturedSessionId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "captured_session_id"
        },
        "providerId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "provider_id"
        },
        "sourceMessageId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "source_message_id"
        },
        "sourceMessageKey": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "source_message_key"
        },
        "sourceFingerprint": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "source_fingerprint"
        },
        "role": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "contentText": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "content_text"
        },
        "contentJson": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "content_json"
        },
        "sequenceNumber": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "sequence_number"
        },
        "sourceCreatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "source_created_at"
        },
        "metadataJson": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "metadata_json"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "captured_session_messages"
} as const;
const capturedSessionSourceSnapshotsTable = {
    "name": "capturedSessionSourceSnapshots",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "capturedSessionId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "captured_session_id"
        },
        "syncBatchId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "sync_batch_id"
        },
        "providerId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "provider_id"
        },
        "sourceUrl": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "source_url"
        },
        "parserVersion": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "parser_version"
        },
        "fileObjectId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "file_object_id"
        },
        "capturedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "captured_at"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "captured_session_source_snapshots"
} as const;
const capturedSessionsTable = {
    "name": "capturedSessions",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "workspaceSlug": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_slug"
        },
        "providerId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "provider_id"
        },
        "captureClientId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "capture_client_id"
        },
        "kind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "sourceUrl": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "source_url"
        },
        "sourceSessionId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "source_session_id"
        },
        "sourceSessionKey": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "source_session_key"
        },
        "title": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "firstCapturedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "first_captured_at"
        },
        "lastSyncedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "last_synced_at"
        },
        "metadataJson": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "metadata_json"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "captured_sessions"
} as const;
const fileObjectsTable = {
    "name": "fileObjects",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "workspaceSlug": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "workspace_slug"
        },
        "visibility": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "usageKind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "usage_kind"
        },
        "publicAssetId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "public_asset_id"
        },
        "contentType": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "content_type"
        },
        "byteSize": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "byte_size"
        },
        "sha256": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "originalFilename": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "original_filename"
        },
        "storageStatus": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "storage_status"
        },
        "createdByKind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "created_by_kind"
        },
        "createdById": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "created_by_id"
        },
        "deletedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "deleted_at"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "file_objects"
} as const;
const sessionCaptureSyncEventsTable = {
    "name": "sessionCaptureSyncEvents",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "captureClientId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "capture_client_id"
        },
        "capturedSessionId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "captured_session_id"
        },
        "syncBatchId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "sync_batch_id"
        },
        "providerId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "provider_id"
        },
        "status": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "messageCount": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "message_count"
        },
        "artifactCount": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "artifact_count"
        },
        "errorCode": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "error_code"
        },
        "errorMessage": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "error_message"
        },
        "metadataJson": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "metadata_json"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "session_capture_sync_events"
} as const;
const usersTable = {
    "name": "users",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "displayName": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "display_name"
        },
        "email": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "emailNormalized": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "email_normalized"
        },
        "emailVerifiedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "email_verified_at"
        },
        "avatarFileObjectId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "avatar_file_object_id"
        },
        "lastLoginAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "last_login_at"
        },
        "primaryChannelKind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "primary_channel_kind"
        },
        "primaryChannelRef": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "primary_channel_ref"
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "metadataJson": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "metadata_json"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const workspaceMembershipsTable = {
    "name": "workspaceMemberships",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "workspaceSlug": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_slug"
        },
        "principalKind": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "principal_kind"
        },
        "principalId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "principal_id"
        },
        "role": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "workspace_memberships"
} as const;
const workspacesTable = {
    "name": "workspaces",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceSlug": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_slug"
        },
        "workspaceName": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_name"
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "metadataJson": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "metadata_json"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "capturedSessionArtifacts": capturedSessionArtifactsTable,
        "capturedSessionMessages": capturedSessionMessagesTable,
        "capturedSessionSourceSnapshots": capturedSessionSourceSnapshotsTable,
        "capturedSessions": capturedSessionsTable,
        "fileObjects": fileObjectsTable,
        "sessionCaptureSyncEvents": sessionCaptureSyncEventsTable,
        "users": usersTable,
        "workspaceMemberships": workspaceMembershipsTable,
        "workspaces": workspacesTable
    },
    "relationships": {},
    "enableLegacyQueries": false,
    "enableLegacyMutators": false
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "capturedSessionArtifacts" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CapturedSessionArtifact = Row<(typeof schema)["tables"]["capturedSessionArtifacts"]>;
/**
 * Represents a row from the "capturedSessionMessages" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CapturedSessionMessage = Row<(typeof schema)["tables"]["capturedSessionMessages"]>;
/**
 * Represents a row from the "capturedSessionSourceSnapshots" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CapturedSessionSourceSnapshot = Row<(typeof schema)["tables"]["capturedSessionSourceSnapshots"]>;
/**
 * Represents a row from the "capturedSessions" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CapturedSession = Row<(typeof schema)["tables"]["capturedSessions"]>;
/**
 * Represents a row from the "fileObjects" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type FileObject = Row<(typeof schema)["tables"]["fileObjects"]>;
/**
 * Represents a row from the "sessionCaptureSyncEvents" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type SessionCaptureSyncEvent = Row<(typeof schema)["tables"]["sessionCaptureSyncEvents"]>;
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["users"]>;
/**
 * Represents a row from the "workspaceMemberships" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type WorkspaceMembership = Row<(typeof schema)["tables"]["workspaceMemberships"]>;
/**
 * Represents a row from the "workspaces" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Workspace = Row<(typeof schema)["tables"]["workspaces"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' { interface DefaultTypes { schema: Schema; } }
