// @generated drizzle-zero signature:sha256:f7c1eac924a3e000521d91b795bd37676be498daf853a0339e7b29f7a2d7f234
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const fileObjectsTable = {
    "name": "fileObjects",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "workspaceSlug": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "workspace_slug"
        },
        "visibility": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "usageKind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "usage_kind"
        },
        "publicAssetId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "public_asset_id"
        },
        "contentType": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "content_type"
        },
        "byteSize": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "byte_size"
        },
        "sha256": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "originalFilename": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "original_filename"
        },
        "storageStatus": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "storage_status"
        },
        "createdByKind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "created_by_kind"
        },
        "createdById": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "created_by_id"
        },
        "deletedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "deleted_at"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "file_objects"
} as const;
const usersTable = {
    "name": "users",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "displayName": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "display_name"
        },
        "email": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "emailNormalized": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "email_normalized"
        },
        "emailVerifiedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "email_verified_at"
        },
        "avatarFileObjectId": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "avatar_file_object_id"
        },
        "lastLoginAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "last_login_at"
        },
        "primaryChannelKind": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "primary_channel_kind"
        },
        "primaryChannelRef": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "primary_channel_ref"
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "metadataJson": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "metadata_json"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const workspaceMembershipsTable = {
    "name": "workspaceMemberships",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_id"
        },
        "workspaceSlug": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_slug"
        },
        "principalKind": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "principal_kind"
        },
        "principalId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "principal_id"
        },
        "role": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "workspace_memberships"
} as const;
const workspacesTable = {
    "name": "workspaces",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "workspaceSlug": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_slug"
        },
        "workspaceName": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "workspace_name"
        },
        "status": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "metadataJson": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "metadata_json"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "fileObjects": fileObjectsTable,
        "users": usersTable,
        "workspaceMemberships": workspaceMembershipsTable,
        "workspaces": workspacesTable
    },
    "relationships": {},
    "enableLegacyQueries": false,
    "enableLegacyMutators": false
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "fileObjects" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type FileObject = Row<(typeof schema)["tables"]["fileObjects"]>;
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["users"]>;
/**
 * Represents a row from the "workspaceMemberships" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type WorkspaceMembership = Row<(typeof schema)["tables"]["workspaceMemberships"]>;
/**
 * Represents a row from the "workspaces" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Workspace = Row<(typeof schema)["tables"]["workspaces"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' { interface DefaultTypes { schema: Schema; } }
