import { drizzleZeroConfig } from "drizzle-zero"

import * as schema from "../core/src/db/schema"

export default drizzleZeroConfig(schema, {
  tables: {
    capturedSessionArtifacts: {
      id: true,
      workspaceId: true,
      capturedSessionId: true,
      capturedMessageId: true,
      fileObjectId: true,
      artifactKind: true,
      sourceArtifactId: true,
      sourceArtifactKey: true,
      title: true,
      contentType: true,
      metadataJson: true,
      createdAt: true,
      updatedAt: true,
    },
    capturedSessionMessages: {
      id: true,
      workspaceId: true,
      capturedSessionId: true,
      providerId: true,
      sourceMessageId: true,
      sourceMessageKey: true,
      sourceFingerprint: true,
      role: true,
      contentText: true,
      contentJson: true,
      sequenceNumber: true,
      sourceCreatedAt: true,
      metadataJson: true,
      createdAt: true,
      updatedAt: true,
    },
    capturedSessionSourceSnapshots: {
      id: true,
      workspaceId: true,
      capturedSessionId: true,
      syncBatchId: true,
      providerId: true,
      sourceUrl: true,
      parserVersion: true,
      fileObjectId: true,
      capturedAt: true,
      createdAt: true,
    },
    capturedSessions: {
      id: true,
      workspaceId: true,
      workspaceSlug: true,
      providerId: true,
      captureClientId: true,
      kind: true,
      sourceUrl: true,
      sourceSessionId: true,
      sourceSessionKey: true,
      title: true,
      status: true,
      firstCapturedAt: true,
      lastSyncedAt: true,
      metadataJson: true,
      createdAt: true,
      updatedAt: true,
    },
    fileObjects: {
      id: true,
      workspaceId: true,
      workspaceSlug: true,
      visibility: true,
      usageKind: true,
      publicAssetId: true,
      originalFilename: true,
      contentType: true,
      byteSize: true,
      sha256: true,
      storageStatus: true,
      createdById: true,
      createdByKind: true,
      createdAt: true,
      updatedAt: true,
      deletedAt: true,
    },
    users: {
      id: true,
      displayName: true,
      email: true,
      emailNormalized: true,
      emailVerifiedAt: true,
      avatarFileObjectId: true,
      lastLoginAt: true,
      primaryChannelKind: true,
      primaryChannelRef: true,
      status: true,
      metadataJson: true,
      createdAt: true,
      updatedAt: true,
    },
    sessionCaptureSyncEvents: {
      id: true,
      workspaceId: true,
      captureClientId: true,
      capturedSessionId: true,
      syncBatchId: true,
      providerId: true,
      status: true,
      messageCount: true,
      artifactCount: true,
      errorCode: true,
      errorMessage: true,
      metadataJson: true,
      createdAt: true,
    },
    workspaceMemberships: {
      id: true,
      workspaceId: true,
      workspaceSlug: true,
      principalKind: true,
      principalId: true,
      role: true,
      status: true,
      createdAt: true,
      updatedAt: true,
    },
    workspaces: {
      id: true,
      workspaceSlug: true,
      workspaceName: true,
      status: true,
      metadataJson: true,
      createdAt: true,
      updatedAt: true,
    },
  },
})
