import { drizzleZeroConfig } from "drizzle-zero"

import * as schema from "../core/src/db/schema"

export default drizzleZeroConfig(schema, {
  tables: {
    fileObjects: {
      id: true,
      workspaceId: true,
      workspaceSlug: true,
      visibility: true,
      usageKind: true,
      publicAssetId: true,
      originalFilename: true,
      contentType: true,
      byteSize: true,
      sha256: true,
      storageStatus: true,
      createdById: true,
      createdByKind: true,
      createdAt: true,
      updatedAt: true,
      deletedAt: true,
    },
    users: {
      id: true,
      displayName: true,
      email: true,
      emailNormalized: true,
      emailVerifiedAt: true,
      avatarFileObjectId: true,
      lastLoginAt: true,
      primaryChannelKind: true,
      primaryChannelRef: true,
      status: true,
      metadataJson: true,
      createdAt: true,
      updatedAt: true,
    },
    waAccounts: {
      id: true,
      workspaceId: true,
      displayName: true,
      phoneNumber: true,
      jid: true,
      status: true,
      linkMethod: true,
      mediaDownloadMode: true,
      createdByUserId: true,
      lastConnectedAt: true,
      lastDisconnectedAt: true,
      lastErrorCode: true,
      lastErrorMessage: true,
      createdAt: true,
      updatedAt: true,
    },
    waChats: true,
    waContacts: true,
    waLinkRequests: {
      id: true,
      workspaceId: true,
      accountId: true,
      requestedByUserId: true,
      runnerId: true,
      method: true,
      status: true,
      qrPayload: true,
      pairingCode: true,
      expiresAt: true,
      startedAt: true,
      completedAt: true,
      errorCode: true,
      errorMessage: true,
      createdAt: true,
      updatedAt: true,
    },
    waMedia: {
      id: true,
      workspaceId: true,
      accountId: true,
      messageId: true,
      mediaType: true,
      mimeType: true,
      filename: true,
      byteSize: true,
      sha256: true,
      storageProvider: true,
      storageKey: true,
      downloadStatus: true,
      rawJson: true,
      createdAt: true,
      updatedAt: true,
    },
    waMessages: true,
    waSyncRuns: true,
    workspaceMemberships: {
      id: true,
      workspaceId: true,
      workspaceSlug: true,
      principalKind: true,
      principalId: true,
      role: true,
      status: true,
      createdAt: true,
      updatedAt: true,
    },
    workspaces: {
      id: true,
      workspaceSlug: true,
      workspaceName: true,
      status: true,
      metadataJson: true,
      createdAt: true,
      updatedAt: true,
    },
  },
})
