import { readFileSync } from "node:fs"
import { join } from "node:path"
import { describe, expect, test } from "vitest"

const routerSource = () =>
  readFileSync(join(process.cwd(), "src/domains/settings/server/trpc-router.ts"), "utf8")

describe("settings tRPC router", () => {
  test("keeps normal settings writes and auth security reads on tRPC", () => {
    const source = routerSource()
    const appRouterSource = readFileSync(join(process.cwd(), "src/trpc/router.ts"), "utf8")

    expect(source).toContain("createSettingsRouter")
    expect(source).toContain("profile: router")
    expect(source).toContain("security: router")
    expect(source).toContain("oauthGrants: router")
    expect(source).toContain("apiTokens: router")
    expect(source).toContain("invitations: router")
    expect(source).toContain("members: router")
    expect(source).toContain("workspace: router")
    expect(source).toContain("updateOwnUserProfile(createPostgresUserStore")
    expect(source).toContain("updateWorkspace(createPostgresWorkspaceStore")
    expect(source).toContain("renameWorkspaceSlug(createPostgresWorkspaceStore")
    expect(source).toContain("slugAvailability: protectedProcedure")
    expect(source).toContain("updateSlug: protectedProcedure")
    expect(source).toContain("isOnboardingSlugAvailable")
    expect(source).toContain("listActiveBrowserSessions(createPostgresBrowserAuthStore")
    expect(source).toContain("findUserPasswordHash")
    expect(source).toContain("revokeOtherBrowserSessions(createPostgresBrowserAuthStore")
    expect(source).toContain("revokeOtherBrowserSession(createPostgresBrowserAuthStore")
    expect(source).toContain("revokeSession: protectedProcedure")
    expect(source).toContain("updateBrowserPassword(createPostgresBrowserAuthStore")
    expect(source).toContain("listOwnOAuthGrants(createPostgresOAuthRepository")
    expect(source).toContain("revokeOwnOAuthGrant(createPostgresOAuthRepository")
    expect(source).toContain("updateOwnOAuthGrantScopes(createPostgresOAuthRepository")
    expect(source).toContain("oauthGrantScopeSchema")
    expect(source).toContain("createPersonalApiToken")
    expect(source).toContain("listPersonalApiTokens")
    expect(source).toContain("createWorkspaceInvitation")
    expect(source).toContain("listWorkspaceInvitations")
    expect(source).toContain("revokeWorkspaceInvitation")
    expect(source).toContain("createPostgresInvitationStore")
    expect(source).toContain("revokeWorkspaceInvitationInputSchema")
    expect(source).toContain("listWorkspaceMembers(createPostgresWorkspaceMemberStore")
    expect(source).toContain("updateWorkspaceMember(createPostgresWorkspaceMemberStore")
    expect(source).toContain("disableWorkspaceMember(createPostgresWorkspaceMemberStore")
    expect(source).toContain("reactivateWorkspaceMember(createPostgresWorkspaceMemberStore")
    expect(source).toContain("sendWorkspaceInvitationEmail")
    expect(source).toContain('new URL("/auth/invitations/accept"')
    expect(source).toContain("process.env.CONTEXTBASE_APP_BASE_URL")
    expect(source).toContain("apiTokenScopeSchema")
    expect(source).toContain(".query(({ ctx, input })")
    expect(source).not.toContain("buildPublicAvatarAssetUrl")
    expect(source).not.toContain("avatarPublicAssetId")
    expect(source).not.toContain("requireBrowserBusinessAdminAccess")
    expect(source).not.toContain("createPostgresBusinessStore")
    expect(source).not.toContain("settings.business")
    expect(source).not.toContain("settings.agents")
    expect(source).not.toContain("createPostgresAgentStore")
    expect(source).not.toContain("createWorkspaceAgentApiToken")
    expect(source).toContain("requireBrowserWorkspaceAdminAccess")
    expect(appRouterSource).toContain("settings: settingsRouter")
  })

  test("revokes newly created invitations when email delivery fails", () => {
    const source = routerSource()
    const createIndex = source.indexOf("createWorkspaceInvitation(")
    const sendIndex = source.indexOf("sendWorkspaceInvitationEmail({", createIndex)
    const catchIndex = source.indexOf("catch (deliveryError)", sendIndex)
    const revokeIndex = source.indexOf("revokeWorkspaceInvitation(", catchIndex)
    const rethrowIndex = source.indexOf("throw deliveryError", revokeIndex)
    const compensationBlock = source.slice(catchIndex, rethrowIndex)

    expect(createIndex).toBeGreaterThanOrEqual(0)
    expect(sendIndex).toBeGreaterThan(createIndex)
    expect(catchIndex).toBeGreaterThan(sendIndex)
    expect(revokeIndex).toBeGreaterThan(catchIndex)
    expect(rethrowIndex).toBeGreaterThan(revokeIndex)
    expect(compensationBlock).toContain("createPostgresInvitationStore(client)")
    expect(compensationBlock).toContain("result.invitation.id")
  })
})
