import { readFileSync } from "node:fs"
import { join } from "node:path"
import { describe, expect, test } from "vitest"

describe("page hint stack component", () => {
  test("composes shadcn card and button primitives with overlapping animated cards", () => {
    const source = readFileSync(
      join(process.cwd(), "src/shared/page-hints/PageHintStack.tsx"),
      "utf8",
    )

    expect(source).toContain("Card")
    expect(source).toContain("getMeasuredPageHintExpandedY")
    expect(source).toContain("ResizeObserver")
    expect(source).toContain("cardHeights")
    expect(source).toContain("cardRefs")
    expect(source).toContain('"--page-hint-expanded-y": expandedYByHintKey[item.hint.key]')
    expect(source).toContain("CardHeader")
    expect(source).toContain("CardTitle")
    expect(source).toContain("CardDescription")
    expect(source).toContain("CardFooter")
    expect(source).toContain("Button")
    expect(source).toContain("cardHeights)")
    expect(source).toContain("pageHintResetEventName")
    expect(source).toContain("setDismissedKeys(new Set())")
    expect(source).toContain("STACK_COLLAPSE_CLIP_DELAY_MS")
    expect(source).toContain("collapseClipTimeoutRef")
    expect(source).toContain("isStackExpanded || isStackClipDeferred")
    expect(source).toContain("onMouseEnter={expandPageHints}")
    expect(source).toContain("onMouseLeave={collapsePageHints}")
    expect(source).toContain('"--page-hint-y": "120%"')
    expect(source).toContain('"--page-hint-opacity": "0.8"')
    expect(source).toContain('"--page-hint-scale-x": "1"')
    expect(source).toContain("!isDismissing &&")
    expect(source).not.toContain("translate-y-[calc(100%+2rem)] opacity-80")
    expect(source).not.toContain("translate-x-2 scale-95 opacity-0")
    expect(source).not.toContain("translate-y-3 scale-95 opacity-0")
    expect(source).toContain("absolute right-5 bottom-28 md:bottom-5")
    expect(source).toContain("transition-all duration-300 ease-out")
    expect(source).toContain("motion-reduce:transition-none")
    expect(source).toContain("pointer-events-none")
    expect(source).toContain("pointer-events-auto")
    expect(source).toContain("group/page-hints")
    expect(source).toContain("group-hover/page-hints:pointer-events-auto")
    expect(source).toContain('aria-hidden="true"')
    expect(source).toContain("overflow-hidden")
    expect(source).toContain("z-10 overflow-visible h-[42rem]")
    expect(source).toContain('? "h-[42rem] overflow-hidden"')
    expect(source).not.toContain('? "h-[42rem] overflow-visible"')
    expect(source).not.toContain("group-hover/page-hints:h-[42rem]")
    expect(source).not.toContain("group-hover/page-hints:overflow-visible")
    expect(source).toContain("const [topItem, ...backgroundItems] = items")
    expect(source).toContain("{backgroundItems.map(renderHintCard)}")
    expect(source).toContain("{topItem ? renderHintCard(topItem) : null}")
    expect(source).toContain("absolute bottom-0 -left-2")
    expect(source).toContain("w-[calc(100%+1rem)]")
    expect(source).toContain("h-[calc(var(--page-hint-collapsed-stack-height)+0.5rem)]")
    expect(source).toContain("right-2 bottom-0 left-2 w-auto")
    expect(source).toContain('"--page-hint-collapsed-stack-height"')
    expect(source).toContain("z-0")
    expect(source).toContain("z-10 overflow-visible")
    expect(source).toContain("group-hover/page-hints:translate-y-[var(--page-hint-expanded-y)]")
    expect(source).toContain("scale-x-[var(--page-hint-scale-x)]")
    expect(source).toContain("group-hover/page-hints:scale-x-100")
    expect(source).toContain("origin-bottom")
    expect(source).not.toContain("h-64")
    expect(source).toContain('aria-label="Page guidance"')
    expect(source).toContain("rounded-xl")
    expect(source).toContain("shadow-[0_1px_2px_rgb(0_0_0/0.02)]")
    expect(source).toContain("bg-popover py-0")
    expect(source).toContain('<div className="flex items-center gap-2">')
    expect(source).toContain('LightbulbIcon className="size-3.5 shrink-0 text-muted-foreground"')
    expect(source).toContain('<CardTitle className="text-sm leading-5">')
    expect(source).toContain('CardFooter className="justify-end px-4 pt-0 pb-2.5"')
    expect(source).not.toContain('<span className="flex size-7')
    expect(source).not.toContain("bg-popover/95")
    expect(source).not.toContain("rounded-lg")
    expect(source).not.toContain('CardFooter className="justify-end px-4 pt-1 pb-4"')
    expect(source).not.toContain("XIcon")
    expect(source).not.toContain('aria-label="Dismiss guidance"')
    expect(source).not.toContain("grid-cols-[auto_1fr_auto]")
    expect(source).not.toContain("scale-[var(--page-hint-scale)]")
    expect(source).not.toContain("group-hover/page-hints:scale-100")
    expect(source).not.toContain("STACK_EXPANDED_OFFSET_PX")
    expect(source).not.toContain("shadow-[0_1px_3px")
    expect(source).not.toContain("shadow-[0_8px_22px")
    expect(source).not.toContain("shadow-[0_18px_50px")
  })
})
